import type { ThaiConsonantEntry } from "./content";

/**
 * Hochklasse-Konsonanten (11). Entscheidend für spätere Tonregeln.
 * Reihenfolge: gängige Lernreihenfolge.
 */
export const HIGH_CLASS_CONSONANTS: ThaiConsonantEntry[] = [
  {
    char: "ข",
    class: "high",
    mnemonicThai: "ข.ไข่",
    mnemonicRtgs: "kho khai",
    mnemonicDe: "Ei",
    initialSoundDe:
      "aspiriertes „kh“ (mit merklichem Hauch, stärker als bei ก); nicht wie „sch“",
    exampleFromVocab: {
      thai: "ข้าว",
      german: "Reis",
      transliteration: "khao",
    },
    ttsPhraseThai: "ขอไข่",
  },
  {
    char: "ฉ",
    class: "high",
    mnemonicThai: "ฉ.ฉิ่ง",
    mnemonicRtgs: "cho ching",
    mnemonicDe: "Becken (Musik)",
    initialSoundDe: "zisch-artiges „tsch“ (härter/knapper als weiches „dsch“)",
    exampleFromVocab: {
      thai: "ฉัน",
      german: "ich",
      transliteration: "chan",
    },
    ttsPhraseThai: "ฉอฉิ่ง",
  },
  {
    char: "ฐ",
    class: "high",
    mnemonicThai: "ฐ.ฐาน",
    mnemonicRtgs: "tho than",
    mnemonicDe: "Sockel/Säule",
    initialSoundDe: "aspiriertes „th“ (Zungenspitze wie engl. „think“), nicht wie „t“",
    exampleNoteDe:
      "Selten in Alltagsworten. Laut wie ถ (gleiche Artikulation, andere Tonklasse).",
    ttsPhraseThai: "ฐอฐาน",
  },
  {
    char: "ถ",
    class: "high",
    mnemonicThai: "ถ.ถุง",
    mnemonicRtgs: "tho thung",
    mnemonicDe: "Sack/Beutel",
    initialSoundDe: "aspiriertes „th“ (Zungenspitze), nicht deutsch „t“",
    exampleFromVocab: {
      thai: "ถูก",
      german: "richtig/günstig",
      transliteration: "thuuk",
    },
    ttsPhraseThai: "ถอถุง",
  },
  {
    char: "ผ",
    class: "high",
    mnemonicThai: "ผ.ผึ้ง",
    mnemonicRtgs: "pho phueng",
    mnemonicDe: "Biene",
    initialSoundDe: "aspiriertes „ph“ (mit Hauch), nicht wie deutsches „pf“",
    exampleFromVocab: {
      thai: "ผู้หญิง",
      german: "Frau",
      transliteration: "phuu ying",
    },
    ttsPhraseThai: "ผอผึ้ง",
  },
  {
    char: "ฝ",
    class: "high",
    mnemonicThai: "ฝ.ฝา",
    mnemonicRtgs: "fo fa",
    mnemonicDe: "Deckel",
    initialSoundDe: "„f“ wie im Deutschen",
    exampleFromVocab: {
      thai: "ฝน",
      german: "Regen",
      transliteration: "fon",
    },
    ttsPhraseThai: "ฝอฝา",
  },
  {
    char: "ศ",
    class: "high",
    mnemonicThai: "ศ.ศาลา",
    mnemonicRtgs: "so sala",
    mnemonicDe: "Pavillon",
    initialSoundDe: "„s“ wie in „Sunne“ (stimmhaft nähern: eher scharfes s)",
    exampleNoteDe:
      "Kommt oft in gelehrten oder Sanskrit-Lehnwörtern vor; Laut wie ษ und ส.",
    ttsPhraseThai: "ศอศาลา",
  },
  {
    char: "ษ",
    class: "high",
    mnemonicThai: "ษ.ฤๅษี",
    mnemonicRtgs: "so rue-si",
    mnemonicDe: "Einsiedler (im Namen)",
    initialSoundDe: "„s“ (wie ศ, ส)",
    exampleNoteDe: "Seltenes Zeichen; gleicher Laut wie ศ/ส.",
    ttsPhraseThai: "ษอฤๅษี",
  },
  {
    char: "ส",
    class: "high",
    mnemonicThai: "ส.เสือ",
    mnemonicRtgs: "so sua",
    mnemonicDe: "Tiger",
    initialSoundDe: "„s“ (scharf, ähnlich engl. „see“)",
    exampleFromVocab: {
      thai: "สวัสดี",
      german: "Hallo",
      transliteration: "sa-wat-dii",
    },
    ttsPhraseThai: "สอเสือ",
  },
  {
    char: "ห",
    class: "high",
    mnemonicThai: "ห.หีบ",
    mnemonicRtgs: "ho hip",
    mnemonicDe: "Truhe",
    initialSoundDe: "„h“ wie ausgeatmet (leicht hörbarer Hauch)",
    exampleFromVocab: {
      thai: "ห้า",
      german: "fünf",
      transliteration: "haa",
    },
    ttsPhraseThai: "หอหีบ",
  },
  {
    char: "ฬ",
    class: "high",
    mnemonicThai: "ฬ.จุฬา",
    mnemonicRtgs: "lo chula",
    mnemonicDe: "Drachen (im Namen)",
    initialSoundDe: "„l“ (heute wie ล; sehr seltenes Zeichen)",
    exampleNoteDe: "Fast nur in Wörtern wie จุฬา (Universität). Laut ≈ ล.",
    ttsPhraseThai: "ฬอจุฬา",
  },
];

/**
 * Tiefklasse-Konsonanten (22) im modernen 42-Buchstaben-Grundalphabet.
 * (Zwei historische Zeichen fehlen; ฅ ist extrem selten.)
 */
export const LOW_CLASS_CONSONANTS: ThaiConsonantEntry[] = [
  {
    char: "ค",
    class: "low",
    mnemonicThai: "ค.ควาย",
    mnemonicRtgs: "kho khwai",
    mnemonicDe: "Büffel",
    initialSoundDe:
      "aspiriertes „kh“ (Tiefklasse); klingt ähnlich wie ข, Tonverhalten unterscheidet sich später",
    exampleFromVocab: {
      thai: "ใคร",
      german: "wer",
      transliteration: "khrai",
    },
    ttsPhraseThai: "คอควาย",
  },
  {
    char: "ฅ",
    class: "low",
    mnemonicThai: "ฅ.คน",
    mnemonicRtgs: "kho khon",
    mnemonicDe: "Mensch (im Namen)",
    initialSoundDe: "wie ค (historisch, praktisch ungenutzt)",
    exampleNoteDe:
      "Veraltet; kommt in modernem Thai praktisch nicht vor. Laut = wie ค.",
    ttsPhraseThai: "ฅอคน",
  },
  {
    char: "ฆ",
    class: "low",
    mnemonicThai: "ฆ.ระฆัง",
    mnemonicRtgs: "kho ra-khang",
    mnemonicDe: "Glocke",
    initialSoundDe: "wie ค (selten, oft in religiösen Wörtern)",
    exampleNoteDe: "Selten; gleicher Anlaut wie ค.",
    ttsPhraseThai: "ฆอระฆัง",
  },
  {
    char: "ง",
    class: "low",
    mnemonicThai: "ง.งู",
    mnemonicRtgs: "ngo ngu",
    mnemonicDe: "Schlange",
    initialSoundDe: "velares „ng“ wie in „singen“ (Endlaut), am Silbenanlaut",
    exampleFromVocab: {
      thai: "งาน",
      german: "Arbeit",
      transliteration: "ngaan",
    },
    ttsPhraseThai: "งองู",
  },
  {
    char: "ช",
    class: "low",
    mnemonicThai: "ช.ช้าง",
    mnemonicRtgs: "cho chang",
    mnemonicDe: "Elefant",
    initialSoundDe: "„tsch“ / „dsch“ (weicher als ฉ)",
    exampleFromVocab: {
      thai: "ชา",
      german: "Tee",
      transliteration: "chaa",
    },
    ttsPhraseThai: "ชอช้าง",
  },
  {
    char: "ซ",
    class: "low",
    mnemonicThai: "ซ.โซ่",
    mnemonicRtgs: "so so",
    mnemonicDe: "Kette",
    initialSoundDe: "„s“ (oft etwas weicher/stimmhafter als ส)",
    exampleFromVocab: {
      thai: "ซื้อ",
      german: "kaufen",
      transliteration: "sue",
    },
    ttsPhraseThai: "ซอโซ่",
  },
  {
    char: "ฌ",
    class: "low",
    mnemonicThai: "ฌ.เฌอ",
    mnemonicRtgs: "cho choe",
    mnemonicDe: "Baum (im Namen)",
    initialSoundDe: "„tsch“ (selten; ähnlich ช)",
    exampleNoteDe: "Selten in Alltagstexten; Laut nahe ช.",
    ttsPhraseThai: "ฌอเฌอ",
  },
  {
    char: "ญ",
    class: "low",
    mnemonicThai: "ญ.หญิง",
    mnemonicRtgs: "yo ying",
    mnemonicDe: "Frau",
    initialSoundDe: "„y“ wie „j“ in „junge“ (weich)",
    exampleFromVocab: {
      thai: "หญิง",
      german: "Frau",
      transliteration: "ying",
    },
    ttsPhraseThai: "ญอหญิง",
  },
  {
    char: "ฑ",
    class: "low",
    mnemonicThai: "ฑ.มณโฑ",
    mnemonicRtgs: "tho montho",
    mnemonicDe: "Name Montho (im Wort)",
    initialSoundDe: "„th“ oder „t“ in Lehnwörtern (selten)",
    exampleNoteDe: "Sehr selten; oft „th“/„t“ wie bei ถ/ด in Fremdwörtern.",
    ttsPhraseThai: "ฑอมณโฑ",
  },
  {
    char: "ฒ",
    class: "low",
    mnemonicThai: "ฒ.ผู้เฒ่า",
    mnemonicRtgs: "tho phu thao",
    mnemonicDe: "Greis",
    initialSoundDe: "„th“ (selten)",
    exampleNoteDe: "Selten; meist gleiche Artikulationsart wie ถ.",
    ttsPhraseThai: "ฒอผู้เฒ่า",
  },
  {
    char: "ณ",
    class: "low",
    mnemonicThai: "ณ.เณร",
    mnemonicRtgs: "no neen",
    mnemonicDe: "Novize",
    initialSoundDe: "„n“ wie „Name“",
    exampleNoteDe: "Häufiger in formeller Sprache und Eigennamen; Laut = น.",
    ttsPhraseThai: "ณอเณร",
  },
  {
    char: "น",
    class: "low",
    mnemonicThai: "น.หนู",
    mnemonicRtgs: "no nu",
    mnemonicDe: "Maus",
    initialSoundDe: "„n“",
    exampleFromVocab: {
      thai: "น้ำ",
      german: "Wasser",
      transliteration: "nam",
    },
    ttsPhraseThai: "นอหนู",
  },
  {
    char: "ธ",
    class: "low",
    mnemonicThai: "ธ.ธง",
    mnemonicRtgs: "tho thong",
    mnemonicDe: "Fahne",
    initialSoundDe: "„th“ (Zungenspitze) oder „t“ in festen Ausdrücken",
    exampleNoteDe: "Oft in Wörtern wie ธรรม; Laut wie ถ.",
    ttsPhraseThai: "ธอธง",
  },
  {
    char: "พ",
    class: "low",
    mnemonicThai: "พ.พาน",
    mnemonicRtgs: "pho phan",
    mnemonicDe: "Tablett (Opfer)",
    initialSoundDe: "aspiriertes „ph“ (wie ผ, Tiefklasse)",
    exampleFromVocab: {
      thai: "พรุ่งนี้",
      german: "morgen",
      transliteration: "phrung nii",
    },
    ttsPhraseThai: "พอพาน",
  },
  {
    char: "ฟ",
    class: "low",
    mnemonicThai: "ฟ.ฟัน",
    mnemonicRtgs: "fo fan",
    mnemonicDe: "Zahn",
    initialSoundDe: "„f“ (häufig in Lehnwörtern)",
    exampleFromVocab: {
      thai: "ฟัน",
      german: "Zahn",
      transliteration: "fan",
    },
    ttsPhraseThai: "ฟอฟัน",
  },
  {
    char: "ภ",
    class: "low",
    mnemonicThai: "ภ.สำเภา",
    mnemonicRtgs: "pho samphao",
    mnemonicDe: "Dschunke (Schiff)",
    initialSoundDe: "aspiriertes „ph“ (Tiefklasse)",
    exampleFromVocab: {
      thai: "ภาษา",
      german: "Sprache",
      transliteration: "phaasaa",
    },
    ttsPhraseThai: "ภอสำเภา",
  },
  {
    char: "ม",
    class: "low",
    mnemonicThai: "ม.ม้า",
    mnemonicRtgs: "mo ma",
    mnemonicDe: "Pferd",
    initialSoundDe: "„m“",
    exampleFromVocab: {
      thai: "มา",
      german: "kommen",
      transliteration: "maa",
    },
    ttsPhraseThai: "มอม้า",
  },
  {
    char: "ย",
    class: "low",
    mnemonicThai: "ย.ยักษ์",
    mnemonicRtgs: "yo yak",
    mnemonicDe: "Riese",
    initialSoundDe: "„y“ (Halbvokal j)",
    exampleFromVocab: {
      thai: "ยัง",
      german: "noch",
      transliteration: "yang",
    },
    ttsPhraseThai: "ยอยักษ์",
  },
  {
    char: "ร",
    class: "low",
    mnemonicThai: "ร.เรือ",
    mnemonicRtgs: "ro ruea",
    mnemonicDe: "Boot",
    initialSoundDe: "gerolltes „r“ (Zungenspitze)",
    exampleFromVocab: {
      thai: "ร้อน",
      german: "heiß",
      transliteration: "ron",
    },
    ttsPhraseThai: "รอเรือ",
  },
  {
    char: "ล",
    class: "low",
    mnemonicThai: "ล.ลิง",
    mnemonicRtgs: "lo ling",
    mnemonicDe: "Affe",
    initialSoundDe: "„l“",
    exampleFromVocab: {
      thai: "ลูก",
      german: "Kind",
      transliteration: "luuk",
    },
    ttsPhraseThai: "ลอลิง",
  },
  {
    char: "ว",
    class: "low",
    mnemonicThai: "ว.แหวน",
    mnemonicRtgs: "wo waen",
    mnemonicDe: "Ring",
    initialSoundDe: "„w“ / kurzes „u“-Off (Halbvokal)",
    exampleFromVocab: {
      thai: "วัน",
      german: "Tag",
      transliteration: "wan",
    },
    ttsPhraseThai: "วอแหวน",
  },
  {
    char: "ฮ",
    class: "low",
    mnemonicThai: "ฮ.นกฮูก",
    mnemonicRtgs: "ho nok-huk",
    mnemonicDe: "Eule",
    initialSoundDe: "„h“ (oft etwas kehliger als ห)",
    exampleNoteDe: "Kommt seltener als ห vor; oft in Lehnwörtern.",
    ttsPhraseThai: "ฮอนกฮูก",
  },
];
