/**
 * Phase 1: Grundvokale (Vokalzeichen mit ก … oder gängigen Beispielwörtern).
 * Reihenfolge: erst rechts/unten/oben am Konsonanten, dann Präfix-Vokale (เ แ โ), ใ/ไ, ำ.
 */

export interface ThaiVowelEntry {
  /** Groß dargestelltes Zeichen oder Kurznotation (z. B. „เ…“) */
  vowelDisplay: string;
  /** Thai-Name des Vokals */
  nameThai: string;
  nameRtgs: string;
  nameDe: string;
  /** Wo sitzt das Zeichen relativ zum Konsonanten? */
  positionDe: string;
  /** Beispielwort oder -silbe */
  exampleThai: string;
  exampleTransliteration: string;
  exampleGerman: string;
  /** Zusatzinfo (z. B. wenn nicht mit ก) */
  hintDe?: string;
  /** TTS: Thai-Name des Vokals (สระ …), falls Klammern/Zusätze in nameThai die Stimme stören */
  ttsVowelNameThai?: string;
  /** Entspricht meist dem Beispielwort (Beispiel-TTS nutzt direkt exampleThai) */
  ttsPhraseThai: string;
}

export const PHASE1_VOWELS: ThaiVowelEntry[] = [
  {
    vowelDisplay: "า",
    nameThai: "สระ อา",
    nameRtgs: "sara aa",
    nameDe: "langes „a“",
    positionDe: "rechts vom Konsonanten",
    exampleThai: "กา",
    exampleTransliteration: "kaa",
    exampleGerman: "Silbe „kaa“ (wie ein langes a)",
    ttsPhraseThai: "กา",
  },
  {
    vowelDisplay: "ะ",
    nameThai: "สระ อะ",
    nameRtgs: "sara a",
    nameDe: "kurzes „a“",
    positionDe: "rechts vom Konsonanten (oft Silbenende)",
    exampleThai: "กะ",
    exampleTransliteration: "ka",
    exampleGerman: "kurzes „a“ (hier als Silbe)",
    ttsPhraseThai: "กะ",
  },
  {
    vowelDisplay: "ิ",
    nameThai: "สระ อิ",
    nameRtgs: "sara i",
    nameDe: "kurzes „i“",
    positionDe: "über dem Konsonanten",
    exampleThai: "กิน",
    exampleTransliteration: "gin",
    exampleGerman: "essen",
    ttsPhraseThai: "กิน",
  },
  {
    vowelDisplay: "ี",
    nameThai: "สระ อี",
    nameRtgs: "sara ii",
    nameDe: "langes „i“",
    positionDe: "über dem Konsonanten",
    exampleThai: "มี",
    exampleTransliteration: "mii",
    exampleGerman: "haben",
    ttsPhraseThai: "มี",
  },
  {
    vowelDisplay: "ุ",
    nameThai: "สระ อุ",
    nameRtgs: "sara u",
    nameDe: "kurzes „u“",
    positionDe: "unter dem Konsonanten",
    exampleThai: "กุ้ง",
    exampleTransliteration: "gung",
    exampleGerman: "Garnele",
    ttsPhraseThai: "กุ้ง",
  },
  {
    vowelDisplay: "ู",
    nameThai: "สระ อู",
    nameRtgs: "sara uu",
    nameDe: "langes „u“",
    positionDe: "unter dem Konsonanten",
    exampleThai: "กู้",
    exampleTransliteration: "kuu",
    exampleGerman: "borgen / leihen (Silbe)",
    ttsPhraseThai: "กู้",
  },
  {
    vowelDisplay: "เ…",
    nameThai: "สระ เอ",
    nameRtgs: "sara e",
    nameDe: "„e“-Art (Vorderzunge)",
    positionDe: "links vor dem Konsonanten (เ + Konsonant + …)",
    exampleThai: "เก็บ",
    exampleTransliteration: "gep",
    exampleGerman: "aufheben / nehmen",
    hintDe: "Das เ steht vor dem Konsonanten, die Silbe liest sich von links.",
    ttsPhraseThai: "เก็บ",
  },
  {
    vowelDisplay: "แ…",
    nameThai: "สระ แอ",
    nameRtgs: "sara ae",
    nameDe: "offenes „ä“ / „ae“",
    positionDe: "links vor dem Konsonanten (แ ก …)",
    exampleThai: "แม่",
    exampleTransliteration: "mae",
    exampleGerman: "Mutter",
    ttsPhraseThai: "แม่",
  },
  {
    vowelDisplay: "โ…",
    nameThai: "สระ โอ",
    nameRtgs: "sara o",
    nameDe: "„o“",
    positionDe: "links vor dem Konsonanten (โ ก …)",
    exampleThai: "โต๊ะ",
    exampleTransliteration: "to",
    exampleGerman: "Tisch",
    ttsPhraseThai: "โต๊ะ",
  },
  {
    vowelDisplay: "ไ…",
    nameThai: "สระ ไอ",
    nameRtgs: "sara ai",
    nameDe: "Diphthong „ai“",
    positionDe: "links vor dem Konsonanten (ไ ก …)",
    exampleThai: "ไก่",
    exampleTransliteration: "gai",
    exampleGerman: "Huhn",
    ttsPhraseThai: "ไก่",
  },
  {
    vowelDisplay: "ใ…",
    nameThai: "สระ ไอ (ใ-Form)",
    nameRtgs: "sara ai",
    nameDe: "gleicher Laut wie ไ…, andere Schreibung",
    positionDe: "links vor dem Konsonanten (nur wenige Wörter mit ใ)",
    exampleThai: "ใคร",
    exampleTransliteration: "khrai",
    exampleGerman: "wer",
    hintDe: "ใ- kommt nur in wenigen häufigen Wörtern vor (Merken!).",
    ttsVowelNameThai: "สระ ไอ ตัว ใ",
    ttsPhraseThai: "ใคร",
  },
  {
    vowelDisplay: "ำ",
    nameThai: "สระ อำ",
    nameRtgs: "sara am",
    nameDe: "nasaliertes „am“",
    positionDe: "ersetzt rechten Vokal und nasaliert (klingt wie „am“/„ang“)",
    exampleThai: "ทำ",
    exampleTransliteration: "tham",
    exampleGerman: "machen / tun",
    hintDe: "Beispiel mit ท; ำ hängt direkt an den Konsonanten.",
    ttsPhraseThai: "ทำ",
  },
];

/**
 * Phase 2: weitere Vokale – u-/ü-Laute, Han-Akat (kurzes a), Diphthonge und
 * mehrteilige Schreibungen (เ…า, เ…ีย, เ…ือ, ื…อ, เ…อ, เ…ิ…, แ…ะ) plus seltenes ฤ.
 */
export const PHASE2_VOWELS: ThaiVowelEntry[] = [
  {
    vowelDisplay: "ึ",
    nameThai: "สระ อึ",
    nameRtgs: "sara ue",
    nameDe: "kurzes „ü“-artiger Vokal",
    positionDe: "über dem Konsonanten",
    exampleThai: "หมึก",
    exampleTransliteration: "muek",
    exampleGerman: "Tintenfisch / Tinte",
    ttsPhraseThai: "หมึก",
  },
  {
    vowelDisplay: "ื",
    nameThai: "สระ อื",
    nameRtgs: "sara uue",
    nameDe: "langes „ü“-artiger Vokal",
    positionDe: "über dem Konsonanten (oft gefolgt von อ oder Konsonant)",
    exampleThai: "คืน",
    exampleTransliteration: "khuen",
    exampleGerman: "Nacht / zurückgeben",
    hintDe: "Oft bildet ื mit dem nächsten Zeichen eine Silbe (z. B. คืน, มือ).",
    ttsPhraseThai: "คืน",
  },
  {
    vowelDisplay: "ั",
    nameThai: "สระ อะ (ไม้หันอากาศ)",
    nameRtgs: "sara a (mai han akat)",
    nameDe: "kurzes „a“",
    positionDe: "über dem Konsonanten (ไม้หันอากาศ ั)",
    exampleThai: "รับ",
    exampleTransliteration: "rap",
    exampleGerman: "annehmen; höfliche Partikel (am Satzende)",
    hintDe: "Das ั kürzt die Silbe; die Aussprache ist ein kurzes „a“.",
    ttsVowelNameThai: "สระ อะ ไม้หันอากาศ",
    ttsPhraseThai: "รับ",
  },
  {
    vowelDisplay: "เ…า",
    nameThai: "สระ เอา",
    nameRtgs: "sara ao",
    nameDe: "Diphthong „ao“",
    positionDe: "เ links vor dem Konsonanten + า rechts (เ + Konsonant + า)",
    exampleThai: "เขา",
    exampleTransliteration: "khao",
    exampleGerman: "er / sie (höflich); sie (Plural)",
    hintDe: "Die Silbe spannt sich von เ über den Konsonanten bis zum า.",
    ttsPhraseThai: "เขา",
  },
  {
    vowelDisplay: "เ…ีย",
    nameThai: "สระ เอีย",
    nameRtgs: "sara ia",
    nameDe: "Diphthong „ia“",
    positionDe: "เ + Konsonant + ี + ย",
    exampleThai: "เรียน",
    exampleTransliteration: "rian",
    exampleGerman: "lernen / studieren",
    ttsPhraseThai: "เรียน",
  },
  {
    vowelDisplay: "เ…ือ",
    nameThai: "สระ เือ",
    nameRtgs: "sara uea",
    nameDe: "Laut wie „üe“ / „ue“",
    positionDe: "เ + Konsonant + ื + อ",
    exampleThai: "เดือน",
    exampleTransliteration: "duean",
    exampleGerman: "Monat",
    hintDe: "Vier Teile: เ, Konsonant, ื und อ gehören zu einer Silbe.",
    ttsPhraseThai: "เดือน",
  },
  {
    vowelDisplay: "ื…อ",
    nameThai: "สระ อือ",
    nameRtgs: "sara uue + o ang",
    nameDe: "langes „ü“ + leises „o“",
    positionDe: "ื direkt nach dem Konsonanten, danach อ (stumm)",
    exampleThai: "มือ",
    exampleTransliteration: "mue",
    exampleGerman: "Hand",
    hintDe: "Das อ nach ื wird nicht als voller Vokal gesprochen; es schließt die Silbe.",
    ttsPhraseThai: "มือ",
  },
  {
    vowelDisplay: "เ…อ",
    nameThai: "สระ เออ",
    nameRtgs: "sara oe",
    nameDe: "offener Laut „ö“ / „oe“",
    positionDe: "เ vor dem Konsonanten; bei kurzer Silbe oft ohne sichtbares อ",
    exampleThai: "เกิด",
    exampleTransliteration: "koet",
    exampleGerman: "geboren werden; geschehen",
    hintDe: "In offenen Silben siehst du เ + Konsonant + อ (z. B. เธอ). Bei Endkonsonant fällt das อ weg.",
    ttsPhraseThai: "เกิด",
  },
  {
    vowelDisplay: "เ…ิ…",
    nameThai: "สระ เอิ",
    nameRtgs: "sara oei",
    nameDe: "Laut wie „ö“ mit folgendem „i“-Ansatz",
    positionDe: "เ + Konsonant + ิ + … (häufig น am Silbenende)",
    exampleThai: "เงิน",
    exampleTransliteration: "ngoen",
    exampleGerman: "Geld",
    ttsPhraseThai: "เงิน",
  },
  {
    vowelDisplay: "แ…ะ",
    nameThai: "สระ แอะ",
    nameRtgs: "sara ae (short)",
    nameDe: "kurzes offenes „ä“",
    positionDe: "แ vor dem Konsonanten + ะ rechts (kurze Silbe)",
    exampleThai: "แพะ",
    exampleTransliteration: "phae",
    exampleGerman: "Ziege",
    ttsPhraseThai: "แพะ",
  },
  {
    vowelDisplay: "ฤ",
    nameThai: "สระ ฤ",
    nameRtgs: "sara rue",
    nameDe: "Sonderzeichen (selten)",
    positionDe: "eigenes Zeichen; Aussprache vom Wort abhängig",
    exampleThai: "ฤดู",
    exampleTransliteration: "reedu",
    exampleGerman: "Jahreszeit",
    hintDe: "Kommt fast nur in wenigen festen Wörtern vor – zum Erkennen reicht es, es nicht zu fürchten.",
    ttsPhraseThai: "ฤดู",
  },
];
